deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "eu-west-1"
  app: "docker-env"
  env: "DockerEnv-env"
  bucket_name: "elasticbeanstalk-eu-west-1-049144009215"
  bucket_path: "dockerEnv"
  on:
    branch: master
