language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t krychaz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true krychaz/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "dockerEnv"
  env: "DockerEnv-env"
  bucket_name: "elasticbeanstalk-eu-west-1-049144009215"
  bucket_path: "dockerEnv"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
